name: Bug Report
description: Report a bug or unexpected behavior in Laravel Hyper
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a controller with...
        2. Add a Blade view with...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, this happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Samples
      description: Please provide relevant code samples
      render: php
      placeholder: |
        // Controller
        public function index() {
            return hyper()->signals(['test' => 'value']);
        }

  - type: input
    id: php_version
    attributes:
      label: PHP Version
      description: Output of `php -v`
      placeholder: "8.2.0"
    validations:
      required: true

  - type: input
    id: laravel_version
    attributes:
      label: Laravel Version
      description: Output of `php artisan --version`
      placeholder: "Laravel Framework 11.0.0"
    validations:
      required: true

  - type: input
    id: hyper_version
    attributes:
      label: Hyper Version
      description: Your installed version of dancycodes/hyper
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant code samples
          required: true
        - label: I have included my environment details
          required: true
